### PR TITLE
Fix reserved keyword urls

### LINKED ISSUE #122: Paths including reserved keywords error
Example paths that fail:
- http://localhost:5678/constructor
- http://localhost:5678/\_\_proto\_\_
- http://localhost:5678/hasOwnProperty
- http://localhost:5678/toString

Error output:
````
TypeError: Arguments to path.join must be strings
   at path.js:360:15
   at Array.filter (native)
   at Object.exports.join (path.js:358:36)
   at testPath (/Users/n/lingon-example/node_modules/lingon/lib/server.js:35:14)
   at rewriteRequestPath (/Users/n/lingon-example/node_modules/lingon/lib/server.js:48:40)
   at requestHandler (/Users/n/lingon-example/node_modules/lingon/lib/server.js:105:19)
   at Layer.handle [as handle_request] (/Users/n/lingon-example/node_modules/lingon/node_modules/express/lib/router/layer.js:82:5)
   at trim_prefix (/Users/n/lingon-example/node_modules/lingon/node_modules/express/lib/router/index.js:269:13)
   at /Users/n/lingon-example/node_modules/lingon/node_modules/express/lib/router/index.js:236:9
   at Function.proto.process_params (/Users/n/lingon-example/node_modules/lingon/node_modules/express/lib/router/index.js:311:12)
````

### PR DESCRIPTION
**Pull request by jpettersson**
This PR resolves #122 

@philipvonbargen Can you review?

### CODE REVIEW

**Comment by jpettersson** [comment]
@philipvonbargen Hold off until the tests pass..

File: lib/environment.js [hunk 1]
```diff
@@ -8,94 +8,35 @@ var ENV = function(opts) {
...
-    // Should the path be ignored based on the ignorePrefix?
-    var matches = _this.ignorePrefixPattern.exec(filePath);
-    if (matches) {
-      return;
-    }
-
-    // Should the path be filtered out because it's not 
-    // in the requested paths?
-    var whitelisted = true;
+  recursiveReaddir(_this.sourcePath, ['_*'], function (err, files) {
```
Comment (jpettersson) [inline lib/environment.js]: Woops, yes!

File: lib/server.js [hunk 2]
```diff
@@ -45,12 +45,12 @@ var server = function(lingon, ip, port) {
 
     // If we don't have a cached path, or if it's no longer valid:
     // let's find it by searching all the possible filenames
-    if(!pathCache[requestFilePath] || !testPath(pathCache[requestFilePath])) {
+    if(!pathCache["CACHE_" + requestFilePath] || !testPath(pathCache["CACHE_" + requestFilePath])) {
```
Comment (jpettersson) [inline lib/server.js]: Yeah, we should add a linter step to catch these..

File: lib/environment.js (hunk 1 above)
Comment (jpettersson) [inline lib/environment.js]: I fixed this in the latest version. Had to modify the recursive-readdir library (and vendor it) since it did not support RegExp objects. It would be a breaking change in Lingon to switch from RegExp objects to glob patterns for the ignorePrefixPattern value. 

I'll work on a proposed PR for the recursive-readdir project to allow both RegExp instances and globs.
